# Generated by Django 4.1.7 on 2023-03-31 15:29

from django.db import migrations, models
import share.models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to=share.models.update_filename),
        ),
    ]
