# Generated by Django 4.1.7 on 2023-04-09 04:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_sharemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='file_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sharemodel',
            name='shared_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
