# Generated by Django 4.1.7 on 2023-04-24 08:09

from django.db import migrations, models
import share.models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_filemodel_file_type_sharemodel_shared_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='encrypted_data',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(blank=True, upload_to=share.models.update_filename),
        ),
    ]
